name: deploy to remote

on:
  push:
    #    branches-ignore:
    #      - "**"
    tags:
      - "v*"

jobs:
  deploy_on_win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      #Electron Builder Action
      #https://github.com/samuelmeuli/action-electron-builder
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: dist:win
# Old
#      - run: npm run dist:win-never
#      - name: create release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          draft: true
#          files: |
#            dist/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# m1対応していない
#  deploy_on_mac:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set Python 3.10
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.10"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#      - name: Set Node.js 18
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18
#
#      - run: npm ci
#      - run: npm run dist:mac-m1

#    - name: create release
#      uses: softprops/action-gh-release@v1
#      if: startsWith(github.ref, 'refs/tags/')
#      with:
#        draft: true
#        files: |
#          dist/*.dmg
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
